### ISSUE TITLE
Give the user a sense of progress 

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/borzoi#52]
Add a progress bar of some sort so that the user can get an idea of how far along they are in the story

**Comment by sharon-wang** [comment]
Sample idea
![image](https://user-images.githubusercontent.com/25834218/91253012-c9e49700-e72c-11ea-9277-7424a93dd8a0.png)

**Comment by vezwork** [comment]
![image](https://user-images.githubusercontent.com/11082236/91255370-df07f880-e721-11ea-83a3-22be8ad41944.png)
Updated idea that incorporates issue #43 into this issue.
