### ISSUE TITLE
Write content for landing page

### ISSUE THREAD

**Issue by vezwork** [esse-dev/borzoi#9]
Content includes: title of webpage, introduction to what the webpage does for the user (a creator), links (if relevant), and a "get started" button

**Comment by sharon-wang** [comment]
mockup
![image](https://user-images.githubusercontent.com/25834218/91252223-26df4d80-e72b-11ea-8fb2-833f79c7b797.png)

puzzle piece to begin is draggable to introduce the user to the dragging concept right off the bat, so that they are familiar once they get to the coding step

**Comment by sharon-wang** [comment]
Updated landing page design in #1
